version: '3.8'

services:
  postgres:
    container_name: coofis_assestment
    image: postgres:15.1
    volumes:
      - coofis_assestment_postgres_data:/var/lib/postgresql/data
      - coofis_assestment_postgres_data_backups:/backups
    environment:
      POSTGRES_USER: coofis_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: coofis_assestments_db
    ports:
      - 5432:5432

volumes:
  coofis_assestment_postgres_data: {}
  coofis_assestment_postgres_data_backups: {}
